[package]
name = "nuclei"
version = "0.1.0"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["bastion", "iouring"]
epoll = []
iouring = ["iou", "uring-sys"]

bastion = ["agnostik/runtime_bastion"]
tokio = ["agnostik/runtime_tokio"]
asyncstd = ["agnostik/runtime_asyncstd"]
smol = ["agnostik/runtime_smol"]

[dependencies]
lever = { git = "https://github.com/vertexclique/lever" }
futures = "0.3.5"
futures-util = "0.3.5"
socket2 = { version = "0.3.12", features = ["pair", "unix"] }
libc = "0.2"
pin-utils = "0.1.0"
once_cell = "1.4.0"
agnostik = { path = "../agnostik", default-features = false }

# Other backends
[target.'cfg(target_os = "linux")'.dependencies]
iou = { version = "0.0.0-ringbahn.1", optional = true }
uring-sys = { version = "0.6.1", optional = true }

[dev-dependencies]
anyhow = "1.0.31"
async-h1 = "1.1.2"
async-dup = "1.1.0"
http-types = "1.2.0"
num_cpus = "1.13.0"