[package]
name = "proactor"
version = "0.1.0"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
iouring = []

[dependencies]
lever = { git = "https://github.com/vertexclique/lever" }
futures = "0.3.5"
libc = "0.2"