[package]
name = "proactor"
version = "0.1.0"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
iouring = []

[dependencies]
lever = { git = "https://github.com/vertexclique/lever" }
futures = "0.3.5"
futures-util = "0.3.5"
socket2 = { version = "0.3.12", features = ["pair", "unix"] }
libc = "0.2"
pin-utils = "0.1.0"
once_cell = "1.4.0"