[package]
name = "proactor"
version = "0.1.0"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
iouring = []

[dependencies]
lever = { git = "https://github.com/vertexclique/lever" }
futures = "0.3.5"
futures-util = "0.3.5"
socket2 = { version = "0.3.12", features = ["pair", "unix"] }
libc = "0.2"
pin-utils = "0.1.0"
once_cell = "1.4.0"

[dev-dependencies]
bastion = { git = "https://github.com/bastion-rs/bastion.git" }
anyhow = "1.0.31"
async-h1 = "1.1.2"
async-dup = "1.1.0"
http-types = "1.2.0"