[package]
name = "proactor"
version = "0.1.0"
authors = ["Mahmut Bulut <vertexclique@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
#default = ["epoll"]
default = ["iouring"]
epoll = []
iouring = ["iou", "uring-sys"]

[dependencies]
lever = { git = "https://github.com/vertexclique/lever" }
futures = "0.3.5"
futures-util = "0.3.5"
crossbeam-channel = "0.4.2"
socket2 = { version = "0.3.12", features = ["pair", "unix"] }
libc = "0.2"
pin-utils = "0.1.0"
once_cell = "1.4.0"
bastion = { git = "https://github.com/bastion-rs/bastion.git" }

# Other backends
iou = { version = "0.0.0-ringbahn.1", optional = true }
uring-sys = { version = "0.6.1", optional = true }

[dev-dependencies]
anyhow = "1.0.31"
async-h1 = "2.0.2"
async-dup = "1.1.0"
http-types = "2.2.1"
num_cpus = "1.13.0"
smol = "0.1.18"